name: Publish Docker image to GHCR

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to publish (e.g., 0.1.0)'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for tag push
        id: meta_tag
        if: github.event_name == 'push'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/raw-labs/das-client-postgresql
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Extract metadata for manual dispatch
        id: meta_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/raw-labs/das-client-postgresql
          tags: |
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.meta_tag.outputs.tags }}
            ${{ steps.meta_dispatch.outputs.tags }}
          labels: |
            ${{ steps.meta_tag.outputs.labels }}
            ${{ steps.meta_dispatch.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


