name: Publish Docker image to GHCR

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to publish (e.g., 0.1.0)'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/raw-labs/das-client-postgresql
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_tag}}

      - name: Compute manual tags
        id: manual
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tags=ghcr.io/raw-labs/das-client-postgresql:${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "Computed manual tag: ghcr.io/raw-labs/das-client-postgresql:${{ github.event.inputs.tag }}"
          else
            echo "tags=" >> $GITHUB_OUTPUT
            echo "No manual tag provided; relying on metadata tags"
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.manual.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


